export const PRODUCT_CATEGORIES = [
  "Lighting",
  "Plumbing",
  "Hardware",
  "Appliances",
  "Flooring",
  "Tile",
  "Countertops",
  "Paint",
  "Furniture",
  "Decor",
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

export const SUBCATEGORIES: Record<ProductCategory, string[]> = {
  Lighting: [
    "Pendants",
    "Sconces",
    "Chandeliers",
    "Flush Mount",
    "Semi-Flush Mount",
    "Lamps",
    "Recessed Lighting",
    "Vanity Lighting",
    "Lanterns",
    "Picture Lights",
    "Outdoor Lighting",
  ],
  Plumbing: [
    "Faucets",
    "Pot Fillers",
    "Shower Systems",
    "Shower Trim",
    "Tub Fillers",
    "Tubs",
    "Sinks",
    "Toilets",
    "Drains",
    "Valves",
    "Bathroom Accessories",
  ],
  Hardware: [
    "Cabinet Pulls",
    "Cabinet Knobs",
    "Cabinet Hinges",
    "Cabinet Latches",
    "Appliance Pulls",
    "Door Hardware",
    "Door Hinges",
    "Hooks",
    "Towel Bars",
    "Towel Rings",
    "Toilet Paper Holders",
    "Base & Case",
  ],
  Appliances: [
    "Refrigerators",
    "Freezers",
    "Ranges",
    "Cooktops",
    "Wall Ovens",
    "Microwaves",
    "Dishwashers",
    "Hoods",
    "Coffee Makers",
    "Beverage Centers",
    "Wine Coolers",
    "Washers",
    "Dryers",
  ],
  Flooring: [
    "Wood",
    "Engineered Wood",
    "Stone",
    "Tile",
    "Carpet",
    "Rugs",
    "Vinyl",
    "Concrete",
  ],
  Tile: [
    "Wall Tile",
    "Floor Tile",
    "Backsplash",
    "Shower Wall",
    "Shower Floor",
    "Mosaic",
    "Zellige",
    "Stone Tile",
    "Trim",
  ],
  Countertops: [
    "Slab",
    "Quartzite",
    "Marble",
    "Quartz",
    "Granite",
    "Soapstone",
    "Porcelain",
    "Solid Surface",
    "Butcher Block",
  ],
  Paint: [
    "Wall Paint",
    "Trim Paint",
    "Ceiling Paint",
    "Cabinet Paint",
    "Exterior Paint",
    "Stain",
    "Limewash",
    "Plaster",
  ],
  Furniture: [
    "Seating",
    "Sofas & Sectionals",
    "Chairs",
    "Tables",
    "Coffee Tables",
    "Side Tables",
    "Dining Tables",
    "Beds",
    "Nightstands",
    "Dressers",
    "Storage",
    "Consoles",
    "Desks",
    "Benches & Ottomans",
  ],
  Decor: [
    "Art",
    "Mirrors",
    "Wall Coverings",
    "Textiles",
    "Rugs",
    "Pillows",
    "Window Treatments",
    "Accessories",
    "Vases & Objects",
    "Planters",
  ],
};
