/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProjectManagementRouteImport } from './routes/project-management'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as SpecbooksIndexRouteImport } from './routes/specbooks.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as PresentationsIndexRouteImport } from './routes/presentations.index'
import { Route as HoursIndexRouteImport } from './routes/hours.index'
import { Route as SpecbooksIdRouteImport } from './routes/specbooks.$id'
import { Route as PrototypeDesignBoardRouteImport } from './routes/prototype.design-board'
import { Route as PresentationsIdRouteImport } from './routes/presentations.$id'
import { Route as ExtensionConnectRouteImport } from './routes/extension.connect'
import { Route as ClientFinancialsRouteImport } from './routes/client.financials'
import { Route as CatalogProductIdRouteImport } from './routes/catalog_.$productId'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiUploadRoomImageRouteImport } from './routes/api/upload-room-image'
import { Route as ApiUploadProjectDocumentRouteImport } from './routes/api/upload-project-document'
import { Route as ApiUploadDesignBoardImageRouteImport } from './routes/api/upload-design-board-image'
import { Route as ApiStudioRemindersRouteImport } from './routes/api/studio-reminders'
import { Route as ApiSharedDesignBoardRouteImport } from './routes/api/shared-design-board'
import { Route as ApiScrapeUrlRouteImport } from './routes/api/scrape-url'
import { Route as ApiScrapeMaterialsRouteImport } from './routes/api/scrape-materials'
import { Route as ApiRemoveDesignBoardBackgroundRouteImport } from './routes/api/remove-design-board-background'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiProjectTodosRouteImport } from './routes/api/project-todos'
import { Route as ApiProjectTaskAttachmentRouteImport } from './routes/api/project-task-attachment'
import { Route as ApiProjectManagementRouteImport } from './routes/api/project-management'
import { Route as ApiPresentationBoardRouteImport } from './routes/api/presentation-board'
import { Route as ApiParseInvoicePdfRouteImport } from './routes/api/parse-invoice-pdf'
import { Route as ApiMyTodosRouteImport } from './routes/api/my-todos'
import { Route as ApiMarkFinancialPaymentDueRouteImport } from './routes/api/mark-financial-payment-due'
import { Route as ApiImportMaterialsPdfRouteImport } from './routes/api/import-materials-pdf'
import { Route as ApiImageDataUrlRouteImport } from './routes/api/image-data-url'
import { Route as ApiGenerateRenderingRouteImport } from './routes/api/generate-rendering'
import { Route as ApiDesignBoardQuestionRouteImport } from './routes/api/design-board-question'
import { Route as ApiDesignBoardCommentTodosRouteImport } from './routes/api/design-board-comment-todos'
import { Route as ApiCreateStripePaymentLinkRouteImport } from './routes/api/create-stripe-payment-link'
import { Route as ApiClientDashboardRouteImport } from './routes/api/client-dashboard'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects.$id.index'
import { Route as SpecbooksPublicIdRouteImport } from './routes/specbooks.public.$id'
import { Route as ProjectsIdRenderingsRouteImport } from './routes/projects.$id.renderings'
import { Route as ProjectsIdPresentationRouteImport } from './routes/projects.$id.presentation'
import { Route as ProjectsIdMaterialsRouteImport } from './routes/projects.$id.materials'
import { Route as ProjectsIdFinancialsRouteImport } from './routes/projects.$id.financials'
import { Route as ProjectsIdDesignBoardsRouteImport } from './routes/projects.$id.design-boards'
import { Route as ProjectsIdDesignBoardPresentationRouteImport } from './routes/projects.$id.design-board-presentation'
import { Route as ProjectsIdConstructionDocsRouteImport } from './routes/projects.$id.construction-docs'
import { Route as ProjectsIdApprovalsRouteImport } from './routes/projects.$id.approvals'
import { Route as ClientApprovalsProjectIdRouteImport } from './routes/client.approvals.$projectId'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiQuickbooksSyncInvoiceRouteImport } from './routes/api/quickbooks/sync-invoice'
import { Route as ApiQuickbooksStatusRouteImport } from './routes/api/quickbooks/status'
import { Route as ApiQuickbooksProjectLinkRouteImport } from './routes/api/quickbooks/project-link'
import { Route as ApiQuickbooksDisconnectRouteImport } from './routes/api/quickbooks/disconnect'
import { Route as ApiQuickbooksCustomersRouteImport } from './routes/api/quickbooks/customers'
import { Route as ApiQuickbooksConnectUrlRouteImport } from './routes/api/quickbooks/connect-url'
import { Route as ApiQuickbooksCallbackRouteImport } from './routes/api/quickbooks/callback'
import { Route as ApiExtensionProjectsRouteImport } from './routes/api/extension/projects'
import { Route as ApiExtensionPricesRouteImport } from './routes/api/extension/prices'
import { Route as ApiExtensionImportProductRouteImport } from './routes/api/extension/import-product'
import { Route as ApiExtensionConnectTokenRouteImport } from './routes/api/extension/connect-token'
import { Route as ApiExtensionBoardPagesRouteImport } from './routes/api/extension/board-pages'
import { Route as ProjectsIdRoomsRoomIdRouteImport } from './routes/projects.$id.rooms.$roomId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectManagementRoute = ProjectManagementRouteImport.update({
  id: '/project-management',
  path: '/project-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecbooksIndexRoute = SpecbooksIndexRouteImport.update({
  id: '/specbooks/',
  path: '/specbooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/presentations/',
  path: '/presentations/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursIndexRoute = HoursIndexRouteImport.update({
  id: '/hours/',
  path: '/hours/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecbooksIdRoute = SpecbooksIdRouteImport.update({
  id: '/specbooks/$id',
  path: '/specbooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeDesignBoardRoute = PrototypeDesignBoardRouteImport.update({
  id: '/prototype/design-board',
  path: '/prototype/design-board',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIdRoute = PresentationsIdRouteImport.update({
  id: '/presentations/$id',
  path: '/presentations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionConnectRoute = ExtensionConnectRouteImport.update({
  id: '/extension/connect',
  path: '/extension/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientFinancialsRoute = ClientFinancialsRouteImport.update({
  id: '/client/financials',
  path: '/client/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogProductIdRoute = CatalogProductIdRouteImport.update({
  id: '/catalog_/$productId',
  path: '/catalog/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoomImageRoute = ApiUploadRoomImageRouteImport.update({
  id: '/api/upload-room-image',
  path: '/api/upload-room-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadProjectDocumentRoute =
  ApiUploadProjectDocumentRouteImport.update({
    id: '/api/upload-project-document',
    path: '/api/upload-project-document',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUploadDesignBoardImageRoute =
  ApiUploadDesignBoardImageRouteImport.update({
    id: '/api/upload-design-board-image',
    path: '/api/upload-design-board-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStudioRemindersRoute = ApiStudioRemindersRouteImport.update({
  id: '/api/studio-reminders',
  path: '/api/studio-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSharedDesignBoardRoute = ApiSharedDesignBoardRouteImport.update({
  id: '/api/shared-design-board',
  path: '/api/shared-design-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeUrlRoute = ApiScrapeUrlRouteImport.update({
  id: '/api/scrape-url',
  path: '/api/scrape-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeMaterialsRoute = ApiScrapeMaterialsRouteImport.update({
  id: '/api/scrape-materials',
  path: '/api/scrape-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoveDesignBoardBackgroundRoute =
  ApiRemoveDesignBoardBackgroundRouteImport.update({
    id: '/api/remove-design-board-background',
    path: '/api/remove-design-board-background',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectTodosRoute = ApiProjectTodosRouteImport.update({
  id: '/api/project-todos',
  path: '/api/project-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectTaskAttachmentRoute =
  ApiProjectTaskAttachmentRouteImport.update({
    id: '/api/project-task-attachment',
    path: '/api/project-task-attachment',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiProjectManagementRoute = ApiProjectManagementRouteImport.update({
  id: '/api/project-management',
  path: '/api/project-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPresentationBoardRoute = ApiPresentationBoardRouteImport.update({
  id: '/api/presentation-board',
  path: '/api/presentation-board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseInvoicePdfRoute = ApiParseInvoicePdfRouteImport.update({
  id: '/api/parse-invoice-pdf',
  path: '/api/parse-invoice-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyTodosRoute = ApiMyTodosRouteImport.update({
  id: '/api/my-todos',
  path: '/api/my-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarkFinancialPaymentDueRoute =
  ApiMarkFinancialPaymentDueRouteImport.update({
    id: '/api/mark-financial-payment-due',
    path: '/api/mark-financial-payment-due',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiImportMaterialsPdfRoute = ApiImportMaterialsPdfRouteImport.update({
  id: '/api/import-materials-pdf',
  path: '/api/import-materials-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageDataUrlRoute = ApiImageDataUrlRouteImport.update({
  id: '/api/image-data-url',
  path: '/api/image-data-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRenderingRoute = ApiGenerateRenderingRouteImport.update({
  id: '/api/generate-rendering',
  path: '/api/generate-rendering',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesignBoardQuestionRoute = ApiDesignBoardQuestionRouteImport.update({
  id: '/api/design-board-question',
  path: '/api/design-board-question',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesignBoardCommentTodosRoute =
  ApiDesignBoardCommentTodosRouteImport.update({
    id: '/api/design-board-comment-todos',
    path: '/api/design-board-comment-todos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCreateStripePaymentLinkRoute =
  ApiCreateStripePaymentLinkRouteImport.update({
    id: '/api/create-stripe-payment-link',
    path: '/api/create-stripe-payment-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiClientDashboardRoute = ApiClientDashboardRouteImport.update({
  id: '/api/client-dashboard',
  path: '/api/client-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecbooksPublicIdRoute = SpecbooksPublicIdRouteImport.update({
  id: '/specbooks/public/$id',
  path: '/specbooks/public/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRenderingsRoute = ProjectsIdRenderingsRouteImport.update({
  id: '/projects/$id/renderings',
  path: '/projects/$id/renderings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdPresentationRoute = ProjectsIdPresentationRouteImport.update({
  id: '/projects/$id/presentation',
  path: '/projects/$id/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdMaterialsRoute = ProjectsIdMaterialsRouteImport.update({
  id: '/projects/$id/materials',
  path: '/projects/$id/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdFinancialsRoute = ProjectsIdFinancialsRouteImport.update({
  id: '/projects/$id/financials',
  path: '/projects/$id/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdDesignBoardsRoute = ProjectsIdDesignBoardsRouteImport.update({
  id: '/projects/$id/design-boards',
  path: '/projects/$id/design-boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdDesignBoardPresentationRoute =
  ProjectsIdDesignBoardPresentationRouteImport.update({
    id: '/projects/$id/design-board-presentation',
    path: '/projects/$id/design-board-presentation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdConstructionDocsRoute =
  ProjectsIdConstructionDocsRouteImport.update({
    id: '/projects/$id/construction-docs',
    path: '/projects/$id/construction-docs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdApprovalsRoute = ProjectsIdApprovalsRouteImport.update({
  id: '/projects/$id/approvals',
  path: '/projects/$id/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientApprovalsProjectIdRoute =
  ClientApprovalsProjectIdRouteImport.update({
    id: '/client/approvals/$projectId',
    path: '/client/approvals/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickbooksSyncInvoiceRoute =
  ApiQuickbooksSyncInvoiceRouteImport.update({
    id: '/api/quickbooks/sync-invoice',
    path: '/api/quickbooks/sync-invoice',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuickbooksStatusRoute = ApiQuickbooksStatusRouteImport.update({
  id: '/api/quickbooks/status',
  path: '/api/quickbooks/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickbooksProjectLinkRoute =
  ApiQuickbooksProjectLinkRouteImport.update({
    id: '/api/quickbooks/project-link',
    path: '/api/quickbooks/project-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiQuickbooksDisconnectRoute = ApiQuickbooksDisconnectRouteImport.update({
  id: '/api/quickbooks/disconnect',
  path: '/api/quickbooks/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickbooksCustomersRoute = ApiQuickbooksCustomersRouteImport.update({
  id: '/api/quickbooks/customers',
  path: '/api/quickbooks/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickbooksConnectUrlRoute = ApiQuickbooksConnectUrlRouteImport.update({
  id: '/api/quickbooks/connect-url',
  path: '/api/quickbooks/connect-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuickbooksCallbackRoute = ApiQuickbooksCallbackRouteImport.update({
  id: '/api/quickbooks/callback',
  path: '/api/quickbooks/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionProjectsRoute = ApiExtensionProjectsRouteImport.update({
  id: '/api/extension/projects',
  path: '/api/extension/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionPricesRoute = ApiExtensionPricesRouteImport.update({
  id: '/api/extension/prices',
  path: '/api/extension/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionImportProductRoute =
  ApiExtensionImportProductRouteImport.update({
    id: '/api/extension/import-product',
    path: '/api/extension/import-product',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExtensionConnectTokenRoute =
  ApiExtensionConnectTokenRouteImport.update({
    id: '/api/extension/connect-token',
    path: '/api/extension/connect-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExtensionBoardPagesRoute = ApiExtensionBoardPagesRouteImport.update({
  id: '/api/extension/board-pages',
  path: '/api/extension/board-pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoomsRoomIdRoute = ProjectsIdRoomsRoomIdRouteImport.update({
  id: '/projects/$id/rooms/$roomId',
  path: '/projects/$id/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/financials': typeof FinancialsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/project-management': typeof ProjectManagementRoute
  '/terms': typeof TermsRoute
  '/api/client-dashboard': typeof ApiClientDashboardRoute
  '/api/create-stripe-payment-link': typeof ApiCreateStripePaymentLinkRoute
  '/api/design-board-comment-todos': typeof ApiDesignBoardCommentTodosRoute
  '/api/design-board-question': typeof ApiDesignBoardQuestionRoute
  '/api/generate-rendering': typeof ApiGenerateRenderingRoute
  '/api/image-data-url': typeof ApiImageDataUrlRoute
  '/api/import-materials-pdf': typeof ApiImportMaterialsPdfRoute
  '/api/mark-financial-payment-due': typeof ApiMarkFinancialPaymentDueRoute
  '/api/my-todos': typeof ApiMyTodosRoute
  '/api/parse-invoice-pdf': typeof ApiParseInvoicePdfRoute
  '/api/presentation-board': typeof ApiPresentationBoardRoute
  '/api/project-management': typeof ApiProjectManagementRoute
  '/api/project-task-attachment': typeof ApiProjectTaskAttachmentRoute
  '/api/project-todos': typeof ApiProjectTodosRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/remove-design-board-background': typeof ApiRemoveDesignBoardBackgroundRoute
  '/api/scrape-materials': typeof ApiScrapeMaterialsRoute
  '/api/scrape-url': typeof ApiScrapeUrlRoute
  '/api/shared-design-board': typeof ApiSharedDesignBoardRoute
  '/api/studio-reminders': typeof ApiStudioRemindersRoute
  '/api/upload-design-board-image': typeof ApiUploadDesignBoardImageRoute
  '/api/upload-project-document': typeof ApiUploadProjectDocumentRoute
  '/api/upload-room-image': typeof ApiUploadRoomImageRoute
  '/api/users': typeof ApiUsersRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/client/financials': typeof ClientFinancialsRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/presentations/$id': typeof PresentationsIdRoute
  '/prototype/design-board': typeof PrototypeDesignBoardRoute
  '/specbooks/$id': typeof SpecbooksIdRoute
  '/hours/': typeof HoursIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/specbooks/': typeof SpecbooksIndexRoute
  '/users/': typeof UsersIndexRoute
  '/api/extension/board-pages': typeof ApiExtensionBoardPagesRoute
  '/api/extension/connect-token': typeof ApiExtensionConnectTokenRoute
  '/api/extension/import-product': typeof ApiExtensionImportProductRoute
  '/api/extension/prices': typeof ApiExtensionPricesRoute
  '/api/extension/projects': typeof ApiExtensionProjectsRoute
  '/api/quickbooks/callback': typeof ApiQuickbooksCallbackRoute
  '/api/quickbooks/connect-url': typeof ApiQuickbooksConnectUrlRoute
  '/api/quickbooks/customers': typeof ApiQuickbooksCustomersRoute
  '/api/quickbooks/disconnect': typeof ApiQuickbooksDisconnectRoute
  '/api/quickbooks/project-link': typeof ApiQuickbooksProjectLinkRoute
  '/api/quickbooks/status': typeof ApiQuickbooksStatusRoute
  '/api/quickbooks/sync-invoice': typeof ApiQuickbooksSyncInvoiceRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/client/approvals/$projectId': typeof ClientApprovalsProjectIdRoute
  '/projects/$id/approvals': typeof ProjectsIdApprovalsRoute
  '/projects/$id/construction-docs': typeof ProjectsIdConstructionDocsRoute
  '/projects/$id/design-board-presentation': typeof ProjectsIdDesignBoardPresentationRoute
  '/projects/$id/design-boards': typeof ProjectsIdDesignBoardsRoute
  '/projects/$id/financials': typeof ProjectsIdFinancialsRoute
  '/projects/$id/materials': typeof ProjectsIdMaterialsRoute
  '/projects/$id/presentation': typeof ProjectsIdPresentationRoute
  '/projects/$id/renderings': typeof ProjectsIdRenderingsRoute
  '/specbooks/public/$id': typeof SpecbooksPublicIdRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/rooms/$roomId': typeof ProjectsIdRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/financials': typeof FinancialsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/project-management': typeof ProjectManagementRoute
  '/terms': typeof TermsRoute
  '/api/client-dashboard': typeof ApiClientDashboardRoute
  '/api/create-stripe-payment-link': typeof ApiCreateStripePaymentLinkRoute
  '/api/design-board-comment-todos': typeof ApiDesignBoardCommentTodosRoute
  '/api/design-board-question': typeof ApiDesignBoardQuestionRoute
  '/api/generate-rendering': typeof ApiGenerateRenderingRoute
  '/api/image-data-url': typeof ApiImageDataUrlRoute
  '/api/import-materials-pdf': typeof ApiImportMaterialsPdfRoute
  '/api/mark-financial-payment-due': typeof ApiMarkFinancialPaymentDueRoute
  '/api/my-todos': typeof ApiMyTodosRoute
  '/api/parse-invoice-pdf': typeof ApiParseInvoicePdfRoute
  '/api/presentation-board': typeof ApiPresentationBoardRoute
  '/api/project-management': typeof ApiProjectManagementRoute
  '/api/project-task-attachment': typeof ApiProjectTaskAttachmentRoute
  '/api/project-todos': typeof ApiProjectTodosRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/remove-design-board-background': typeof ApiRemoveDesignBoardBackgroundRoute
  '/api/scrape-materials': typeof ApiScrapeMaterialsRoute
  '/api/scrape-url': typeof ApiScrapeUrlRoute
  '/api/shared-design-board': typeof ApiSharedDesignBoardRoute
  '/api/studio-reminders': typeof ApiStudioRemindersRoute
  '/api/upload-design-board-image': typeof ApiUploadDesignBoardImageRoute
  '/api/upload-project-document': typeof ApiUploadProjectDocumentRoute
  '/api/upload-room-image': typeof ApiUploadRoomImageRoute
  '/api/users': typeof ApiUsersRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/client/financials': typeof ClientFinancialsRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/presentations/$id': typeof PresentationsIdRoute
  '/prototype/design-board': typeof PrototypeDesignBoardRoute
  '/specbooks/$id': typeof SpecbooksIdRoute
  '/hours': typeof HoursIndexRoute
  '/presentations': typeof PresentationsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/specbooks': typeof SpecbooksIndexRoute
  '/users': typeof UsersIndexRoute
  '/api/extension/board-pages': typeof ApiExtensionBoardPagesRoute
  '/api/extension/connect-token': typeof ApiExtensionConnectTokenRoute
  '/api/extension/import-product': typeof ApiExtensionImportProductRoute
  '/api/extension/prices': typeof ApiExtensionPricesRoute
  '/api/extension/projects': typeof ApiExtensionProjectsRoute
  '/api/quickbooks/callback': typeof ApiQuickbooksCallbackRoute
  '/api/quickbooks/connect-url': typeof ApiQuickbooksConnectUrlRoute
  '/api/quickbooks/customers': typeof ApiQuickbooksCustomersRoute
  '/api/quickbooks/disconnect': typeof ApiQuickbooksDisconnectRoute
  '/api/quickbooks/project-link': typeof ApiQuickbooksProjectLinkRoute
  '/api/quickbooks/status': typeof ApiQuickbooksStatusRoute
  '/api/quickbooks/sync-invoice': typeof ApiQuickbooksSyncInvoiceRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/client/approvals/$projectId': typeof ClientApprovalsProjectIdRoute
  '/projects/$id/approvals': typeof ProjectsIdApprovalsRoute
  '/projects/$id/construction-docs': typeof ProjectsIdConstructionDocsRoute
  '/projects/$id/design-board-presentation': typeof ProjectsIdDesignBoardPresentationRoute
  '/projects/$id/design-boards': typeof ProjectsIdDesignBoardsRoute
  '/projects/$id/financials': typeof ProjectsIdFinancialsRoute
  '/projects/$id/materials': typeof ProjectsIdMaterialsRoute
  '/projects/$id/presentation': typeof ProjectsIdPresentationRoute
  '/projects/$id/renderings': typeof ProjectsIdRenderingsRoute
  '/specbooks/public/$id': typeof SpecbooksPublicIdRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/projects/$id/rooms/$roomId': typeof ProjectsIdRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/financials': typeof FinancialsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/procurement': typeof ProcurementRoute
  '/project-management': typeof ProjectManagementRoute
  '/terms': typeof TermsRoute
  '/api/client-dashboard': typeof ApiClientDashboardRoute
  '/api/create-stripe-payment-link': typeof ApiCreateStripePaymentLinkRoute
  '/api/design-board-comment-todos': typeof ApiDesignBoardCommentTodosRoute
  '/api/design-board-question': typeof ApiDesignBoardQuestionRoute
  '/api/generate-rendering': typeof ApiGenerateRenderingRoute
  '/api/image-data-url': typeof ApiImageDataUrlRoute
  '/api/import-materials-pdf': typeof ApiImportMaterialsPdfRoute
  '/api/mark-financial-payment-due': typeof ApiMarkFinancialPaymentDueRoute
  '/api/my-todos': typeof ApiMyTodosRoute
  '/api/parse-invoice-pdf': typeof ApiParseInvoicePdfRoute
  '/api/presentation-board': typeof ApiPresentationBoardRoute
  '/api/project-management': typeof ApiProjectManagementRoute
  '/api/project-task-attachment': typeof ApiProjectTaskAttachmentRoute
  '/api/project-todos': typeof ApiProjectTodosRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/remove-design-board-background': typeof ApiRemoveDesignBoardBackgroundRoute
  '/api/scrape-materials': typeof ApiScrapeMaterialsRoute
  '/api/scrape-url': typeof ApiScrapeUrlRoute
  '/api/shared-design-board': typeof ApiSharedDesignBoardRoute
  '/api/studio-reminders': typeof ApiStudioRemindersRoute
  '/api/upload-design-board-image': typeof ApiUploadDesignBoardImageRoute
  '/api/upload-project-document': typeof ApiUploadProjectDocumentRoute
  '/api/upload-room-image': typeof ApiUploadRoomImageRoute
  '/api/users': typeof ApiUsersRoute
  '/catalog_/$productId': typeof CatalogProductIdRoute
  '/client/financials': typeof ClientFinancialsRoute
  '/extension/connect': typeof ExtensionConnectRoute
  '/presentations/$id': typeof PresentationsIdRoute
  '/prototype/design-board': typeof PrototypeDesignBoardRoute
  '/specbooks/$id': typeof SpecbooksIdRoute
  '/hours/': typeof HoursIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/specbooks/': typeof SpecbooksIndexRoute
  '/users/': typeof UsersIndexRoute
  '/api/extension/board-pages': typeof ApiExtensionBoardPagesRoute
  '/api/extension/connect-token': typeof ApiExtensionConnectTokenRoute
  '/api/extension/import-product': typeof ApiExtensionImportProductRoute
  '/api/extension/prices': typeof ApiExtensionPricesRoute
  '/api/extension/projects': typeof ApiExtensionProjectsRoute
  '/api/quickbooks/callback': typeof ApiQuickbooksCallbackRoute
  '/api/quickbooks/connect-url': typeof ApiQuickbooksConnectUrlRoute
  '/api/quickbooks/customers': typeof ApiQuickbooksCustomersRoute
  '/api/quickbooks/disconnect': typeof ApiQuickbooksDisconnectRoute
  '/api/quickbooks/project-link': typeof ApiQuickbooksProjectLinkRoute
  '/api/quickbooks/status': typeof ApiQuickbooksStatusRoute
  '/api/quickbooks/sync-invoice': typeof ApiQuickbooksSyncInvoiceRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/client/approvals/$projectId': typeof ClientApprovalsProjectIdRoute
  '/projects/$id/approvals': typeof ProjectsIdApprovalsRoute
  '/projects/$id/construction-docs': typeof ProjectsIdConstructionDocsRoute
  '/projects/$id/design-board-presentation': typeof ProjectsIdDesignBoardPresentationRoute
  '/projects/$id/design-boards': typeof ProjectsIdDesignBoardsRoute
  '/projects/$id/financials': typeof ProjectsIdFinancialsRoute
  '/projects/$id/materials': typeof ProjectsIdMaterialsRoute
  '/projects/$id/presentation': typeof ProjectsIdPresentationRoute
  '/projects/$id/renderings': typeof ProjectsIdRenderingsRoute
  '/specbooks/public/$id': typeof SpecbooksPublicIdRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/rooms/$roomId': typeof ProjectsIdRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/financials'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/project-management'
    | '/terms'
    | '/api/client-dashboard'
    | '/api/create-stripe-payment-link'
    | '/api/design-board-comment-todos'
    | '/api/design-board-question'
    | '/api/generate-rendering'
    | '/api/image-data-url'
    | '/api/import-materials-pdf'
    | '/api/mark-financial-payment-due'
    | '/api/my-todos'
    | '/api/parse-invoice-pdf'
    | '/api/presentation-board'
    | '/api/project-management'
    | '/api/project-task-attachment'
    | '/api/project-todos'
    | '/api/projects'
    | '/api/remove-design-board-background'
    | '/api/scrape-materials'
    | '/api/scrape-url'
    | '/api/shared-design-board'
    | '/api/studio-reminders'
    | '/api/upload-design-board-image'
    | '/api/upload-project-document'
    | '/api/upload-room-image'
    | '/api/users'
    | '/catalog/$productId'
    | '/client/financials'
    | '/extension/connect'
    | '/presentations/$id'
    | '/prototype/design-board'
    | '/specbooks/$id'
    | '/hours/'
    | '/presentations/'
    | '/projects/'
    | '/specbooks/'
    | '/users/'
    | '/api/extension/board-pages'
    | '/api/extension/connect-token'
    | '/api/extension/import-product'
    | '/api/extension/prices'
    | '/api/extension/projects'
    | '/api/quickbooks/callback'
    | '/api/quickbooks/connect-url'
    | '/api/quickbooks/customers'
    | '/api/quickbooks/disconnect'
    | '/api/quickbooks/project-link'
    | '/api/quickbooks/status'
    | '/api/quickbooks/sync-invoice'
    | '/api/stripe/webhook'
    | '/client/approvals/$projectId'
    | '/projects/$id/approvals'
    | '/projects/$id/construction-docs'
    | '/projects/$id/design-board-presentation'
    | '/projects/$id/design-boards'
    | '/projects/$id/financials'
    | '/projects/$id/materials'
    | '/projects/$id/presentation'
    | '/projects/$id/renderings'
    | '/specbooks/public/$id'
    | '/projects/$id/'
    | '/projects/$id/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/financials'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/project-management'
    | '/terms'
    | '/api/client-dashboard'
    | '/api/create-stripe-payment-link'
    | '/api/design-board-comment-todos'
    | '/api/design-board-question'
    | '/api/generate-rendering'
    | '/api/image-data-url'
    | '/api/import-materials-pdf'
    | '/api/mark-financial-payment-due'
    | '/api/my-todos'
    | '/api/parse-invoice-pdf'
    | '/api/presentation-board'
    | '/api/project-management'
    | '/api/project-task-attachment'
    | '/api/project-todos'
    | '/api/projects'
    | '/api/remove-design-board-background'
    | '/api/scrape-materials'
    | '/api/scrape-url'
    | '/api/shared-design-board'
    | '/api/studio-reminders'
    | '/api/upload-design-board-image'
    | '/api/upload-project-document'
    | '/api/upload-room-image'
    | '/api/users'
    | '/catalog/$productId'
    | '/client/financials'
    | '/extension/connect'
    | '/presentations/$id'
    | '/prototype/design-board'
    | '/specbooks/$id'
    | '/hours'
    | '/presentations'
    | '/projects'
    | '/specbooks'
    | '/users'
    | '/api/extension/board-pages'
    | '/api/extension/connect-token'
    | '/api/extension/import-product'
    | '/api/extension/prices'
    | '/api/extension/projects'
    | '/api/quickbooks/callback'
    | '/api/quickbooks/connect-url'
    | '/api/quickbooks/customers'
    | '/api/quickbooks/disconnect'
    | '/api/quickbooks/project-link'
    | '/api/quickbooks/status'
    | '/api/quickbooks/sync-invoice'
    | '/api/stripe/webhook'
    | '/client/approvals/$projectId'
    | '/projects/$id/approvals'
    | '/projects/$id/construction-docs'
    | '/projects/$id/design-board-presentation'
    | '/projects/$id/design-boards'
    | '/projects/$id/financials'
    | '/projects/$id/materials'
    | '/projects/$id/presentation'
    | '/projects/$id/renderings'
    | '/specbooks/public/$id'
    | '/projects/$id'
    | '/projects/$id/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/financials'
    | '/login'
    | '/privacy'
    | '/procurement'
    | '/project-management'
    | '/terms'
    | '/api/client-dashboard'
    | '/api/create-stripe-payment-link'
    | '/api/design-board-comment-todos'
    | '/api/design-board-question'
    | '/api/generate-rendering'
    | '/api/image-data-url'
    | '/api/import-materials-pdf'
    | '/api/mark-financial-payment-due'
    | '/api/my-todos'
    | '/api/parse-invoice-pdf'
    | '/api/presentation-board'
    | '/api/project-management'
    | '/api/project-task-attachment'
    | '/api/project-todos'
    | '/api/projects'
    | '/api/remove-design-board-background'
    | '/api/scrape-materials'
    | '/api/scrape-url'
    | '/api/shared-design-board'
    | '/api/studio-reminders'
    | '/api/upload-design-board-image'
    | '/api/upload-project-document'
    | '/api/upload-room-image'
    | '/api/users'
    | '/catalog_/$productId'
    | '/client/financials'
    | '/extension/connect'
    | '/presentations/$id'
    | '/prototype/design-board'
    | '/specbooks/$id'
    | '/hours/'
    | '/presentations/'
    | '/projects/'
    | '/specbooks/'
    | '/users/'
    | '/api/extension/board-pages'
    | '/api/extension/connect-token'
    | '/api/extension/import-product'
    | '/api/extension/prices'
    | '/api/extension/projects'
    | '/api/quickbooks/callback'
    | '/api/quickbooks/connect-url'
    | '/api/quickbooks/customers'
    | '/api/quickbooks/disconnect'
    | '/api/quickbooks/project-link'
    | '/api/quickbooks/status'
    | '/api/quickbooks/sync-invoice'
    | '/api/stripe/webhook'
    | '/client/approvals/$projectId'
    | '/projects/$id/approvals'
    | '/projects/$id/construction-docs'
    | '/projects/$id/design-board-presentation'
    | '/projects/$id/design-boards'
    | '/projects/$id/financials'
    | '/projects/$id/materials'
    | '/projects/$id/presentation'
    | '/projects/$id/renderings'
    | '/specbooks/public/$id'
    | '/projects/$id/'
    | '/projects/$id/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  FinancialsRoute: typeof FinancialsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcurementRoute: typeof ProcurementRoute
  ProjectManagementRoute: typeof ProjectManagementRoute
  TermsRoute: typeof TermsRoute
  ApiClientDashboardRoute: typeof ApiClientDashboardRoute
  ApiCreateStripePaymentLinkRoute: typeof ApiCreateStripePaymentLinkRoute
  ApiDesignBoardCommentTodosRoute: typeof ApiDesignBoardCommentTodosRoute
  ApiDesignBoardQuestionRoute: typeof ApiDesignBoardQuestionRoute
  ApiGenerateRenderingRoute: typeof ApiGenerateRenderingRoute
  ApiImageDataUrlRoute: typeof ApiImageDataUrlRoute
  ApiImportMaterialsPdfRoute: typeof ApiImportMaterialsPdfRoute
  ApiMarkFinancialPaymentDueRoute: typeof ApiMarkFinancialPaymentDueRoute
  ApiMyTodosRoute: typeof ApiMyTodosRoute
  ApiParseInvoicePdfRoute: typeof ApiParseInvoicePdfRoute
  ApiPresentationBoardRoute: typeof ApiPresentationBoardRoute
  ApiProjectManagementRoute: typeof ApiProjectManagementRoute
  ApiProjectTaskAttachmentRoute: typeof ApiProjectTaskAttachmentRoute
  ApiProjectTodosRoute: typeof ApiProjectTodosRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiRemoveDesignBoardBackgroundRoute: typeof ApiRemoveDesignBoardBackgroundRoute
  ApiScrapeMaterialsRoute: typeof ApiScrapeMaterialsRoute
  ApiScrapeUrlRoute: typeof ApiScrapeUrlRoute
  ApiSharedDesignBoardRoute: typeof ApiSharedDesignBoardRoute
  ApiStudioRemindersRoute: typeof ApiStudioRemindersRoute
  ApiUploadDesignBoardImageRoute: typeof ApiUploadDesignBoardImageRoute
  ApiUploadProjectDocumentRoute: typeof ApiUploadProjectDocumentRoute
  ApiUploadRoomImageRoute: typeof ApiUploadRoomImageRoute
  ApiUsersRoute: typeof ApiUsersRoute
  CatalogProductIdRoute: typeof CatalogProductIdRoute
  ClientFinancialsRoute: typeof ClientFinancialsRoute
  ExtensionConnectRoute: typeof ExtensionConnectRoute
  PresentationsIdRoute: typeof PresentationsIdRoute
  PrototypeDesignBoardRoute: typeof PrototypeDesignBoardRoute
  SpecbooksIdRoute: typeof SpecbooksIdRoute
  HoursIndexRoute: typeof HoursIndexRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SpecbooksIndexRoute: typeof SpecbooksIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ApiExtensionBoardPagesRoute: typeof ApiExtensionBoardPagesRoute
  ApiExtensionConnectTokenRoute: typeof ApiExtensionConnectTokenRoute
  ApiExtensionImportProductRoute: typeof ApiExtensionImportProductRoute
  ApiExtensionPricesRoute: typeof ApiExtensionPricesRoute
  ApiExtensionProjectsRoute: typeof ApiExtensionProjectsRoute
  ApiQuickbooksCallbackRoute: typeof ApiQuickbooksCallbackRoute
  ApiQuickbooksConnectUrlRoute: typeof ApiQuickbooksConnectUrlRoute
  ApiQuickbooksCustomersRoute: typeof ApiQuickbooksCustomersRoute
  ApiQuickbooksDisconnectRoute: typeof ApiQuickbooksDisconnectRoute
  ApiQuickbooksProjectLinkRoute: typeof ApiQuickbooksProjectLinkRoute
  ApiQuickbooksStatusRoute: typeof ApiQuickbooksStatusRoute
  ApiQuickbooksSyncInvoiceRoute: typeof ApiQuickbooksSyncInvoiceRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ClientApprovalsProjectIdRoute: typeof ClientApprovalsProjectIdRoute
  ProjectsIdApprovalsRoute: typeof ProjectsIdApprovalsRoute
  ProjectsIdConstructionDocsRoute: typeof ProjectsIdConstructionDocsRoute
  ProjectsIdDesignBoardPresentationRoute: typeof ProjectsIdDesignBoardPresentationRoute
  ProjectsIdDesignBoardsRoute: typeof ProjectsIdDesignBoardsRoute
  ProjectsIdFinancialsRoute: typeof ProjectsIdFinancialsRoute
  ProjectsIdMaterialsRoute: typeof ProjectsIdMaterialsRoute
  ProjectsIdPresentationRoute: typeof ProjectsIdPresentationRoute
  ProjectsIdRenderingsRoute: typeof ProjectsIdRenderingsRoute
  SpecbooksPublicIdRoute: typeof SpecbooksPublicIdRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
  ProjectsIdRoomsRoomIdRoute: typeof ProjectsIdRoomsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-management': {
      id: '/project-management'
      path: '/project-management'
      fullPath: '/project-management'
      preLoaderRoute: typeof ProjectManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specbooks/': {
      id: '/specbooks/'
      path: '/specbooks'
      fullPath: '/specbooks/'
      preLoaderRoute: typeof SpecbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/presentations'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours/': {
      id: '/hours/'
      path: '/hours'
      fullPath: '/hours/'
      preLoaderRoute: typeof HoursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specbooks/$id': {
      id: '/specbooks/$id'
      path: '/specbooks/$id'
      fullPath: '/specbooks/$id'
      preLoaderRoute: typeof SpecbooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/design-board': {
      id: '/prototype/design-board'
      path: '/prototype/design-board'
      fullPath: '/prototype/design-board'
      preLoaderRoute: typeof PrototypeDesignBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/$id': {
      id: '/presentations/$id'
      path: '/presentations/$id'
      fullPath: '/presentations/$id'
      preLoaderRoute: typeof PresentationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension/connect': {
      id: '/extension/connect'
      path: '/extension/connect'
      fullPath: '/extension/connect'
      preLoaderRoute: typeof ExtensionConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/financials': {
      id: '/client/financials'
      path: '/client/financials'
      fullPath: '/client/financials'
      preLoaderRoute: typeof ClientFinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog_/$productId': {
      id: '/catalog_/$productId'
      path: '/catalog/$productId'
      fullPath: '/catalog/$productId'
      preLoaderRoute: typeof CatalogProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-room-image': {
      id: '/api/upload-room-image'
      path: '/api/upload-room-image'
      fullPath: '/api/upload-room-image'
      preLoaderRoute: typeof ApiUploadRoomImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-project-document': {
      id: '/api/upload-project-document'
      path: '/api/upload-project-document'
      fullPath: '/api/upload-project-document'
      preLoaderRoute: typeof ApiUploadProjectDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-design-board-image': {
      id: '/api/upload-design-board-image'
      path: '/api/upload-design-board-image'
      fullPath: '/api/upload-design-board-image'
      preLoaderRoute: typeof ApiUploadDesignBoardImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/studio-reminders': {
      id: '/api/studio-reminders'
      path: '/api/studio-reminders'
      fullPath: '/api/studio-reminders'
      preLoaderRoute: typeof ApiStudioRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shared-design-board': {
      id: '/api/shared-design-board'
      path: '/api/shared-design-board'
      fullPath: '/api/shared-design-board'
      preLoaderRoute: typeof ApiSharedDesignBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape-url': {
      id: '/api/scrape-url'
      path: '/api/scrape-url'
      fullPath: '/api/scrape-url'
      preLoaderRoute: typeof ApiScrapeUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape-materials': {
      id: '/api/scrape-materials'
      path: '/api/scrape-materials'
      fullPath: '/api/scrape-materials'
      preLoaderRoute: typeof ApiScrapeMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remove-design-board-background': {
      id: '/api/remove-design-board-background'
      path: '/api/remove-design-board-background'
      fullPath: '/api/remove-design-board-background'
      preLoaderRoute: typeof ApiRemoveDesignBoardBackgroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project-todos': {
      id: '/api/project-todos'
      path: '/api/project-todos'
      fullPath: '/api/project-todos'
      preLoaderRoute: typeof ApiProjectTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project-task-attachment': {
      id: '/api/project-task-attachment'
      path: '/api/project-task-attachment'
      fullPath: '/api/project-task-attachment'
      preLoaderRoute: typeof ApiProjectTaskAttachmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/project-management': {
      id: '/api/project-management'
      path: '/api/project-management'
      fullPath: '/api/project-management'
      preLoaderRoute: typeof ApiProjectManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/presentation-board': {
      id: '/api/presentation-board'
      path: '/api/presentation-board'
      fullPath: '/api/presentation-board'
      preLoaderRoute: typeof ApiPresentationBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-invoice-pdf': {
      id: '/api/parse-invoice-pdf'
      path: '/api/parse-invoice-pdf'
      fullPath: '/api/parse-invoice-pdf'
      preLoaderRoute: typeof ApiParseInvoicePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my-todos': {
      id: '/api/my-todos'
      path: '/api/my-todos'
      fullPath: '/api/my-todos'
      preLoaderRoute: typeof ApiMyTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mark-financial-payment-due': {
      id: '/api/mark-financial-payment-due'
      path: '/api/mark-financial-payment-due'
      fullPath: '/api/mark-financial-payment-due'
      preLoaderRoute: typeof ApiMarkFinancialPaymentDueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-materials-pdf': {
      id: '/api/import-materials-pdf'
      path: '/api/import-materials-pdf'
      fullPath: '/api/import-materials-pdf'
      preLoaderRoute: typeof ApiImportMaterialsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-data-url': {
      id: '/api/image-data-url'
      path: '/api/image-data-url'
      fullPath: '/api/image-data-url'
      preLoaderRoute: typeof ApiImageDataUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-rendering': {
      id: '/api/generate-rendering'
      path: '/api/generate-rendering'
      fullPath: '/api/generate-rendering'
      preLoaderRoute: typeof ApiGenerateRenderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/design-board-question': {
      id: '/api/design-board-question'
      path: '/api/design-board-question'
      fullPath: '/api/design-board-question'
      preLoaderRoute: typeof ApiDesignBoardQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/design-board-comment-todos': {
      id: '/api/design-board-comment-todos'
      path: '/api/design-board-comment-todos'
      fullPath: '/api/design-board-comment-todos'
      preLoaderRoute: typeof ApiDesignBoardCommentTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-stripe-payment-link': {
      id: '/api/create-stripe-payment-link'
      path: '/api/create-stripe-payment-link'
      fullPath: '/api/create-stripe-payment-link'
      preLoaderRoute: typeof ApiCreateStripePaymentLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-dashboard': {
      id: '/api/client-dashboard'
      path: '/api/client-dashboard'
      fullPath: '/api/client-dashboard'
      preLoaderRoute: typeof ApiClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specbooks/public/$id': {
      id: '/specbooks/public/$id'
      path: '/specbooks/public/$id'
      fullPath: '/specbooks/public/$id'
      preLoaderRoute: typeof SpecbooksPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/renderings': {
      id: '/projects/$id/renderings'
      path: '/projects/$id/renderings'
      fullPath: '/projects/$id/renderings'
      preLoaderRoute: typeof ProjectsIdRenderingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/presentation': {
      id: '/projects/$id/presentation'
      path: '/projects/$id/presentation'
      fullPath: '/projects/$id/presentation'
      preLoaderRoute: typeof ProjectsIdPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/materials': {
      id: '/projects/$id/materials'
      path: '/projects/$id/materials'
      fullPath: '/projects/$id/materials'
      preLoaderRoute: typeof ProjectsIdMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/financials': {
      id: '/projects/$id/financials'
      path: '/projects/$id/financials'
      fullPath: '/projects/$id/financials'
      preLoaderRoute: typeof ProjectsIdFinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/design-boards': {
      id: '/projects/$id/design-boards'
      path: '/projects/$id/design-boards'
      fullPath: '/projects/$id/design-boards'
      preLoaderRoute: typeof ProjectsIdDesignBoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/design-board-presentation': {
      id: '/projects/$id/design-board-presentation'
      path: '/projects/$id/design-board-presentation'
      fullPath: '/projects/$id/design-board-presentation'
      preLoaderRoute: typeof ProjectsIdDesignBoardPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/construction-docs': {
      id: '/projects/$id/construction-docs'
      path: '/projects/$id/construction-docs'
      fullPath: '/projects/$id/construction-docs'
      preLoaderRoute: typeof ProjectsIdConstructionDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/approvals': {
      id: '/projects/$id/approvals'
      path: '/projects/$id/approvals'
      fullPath: '/projects/$id/approvals'
      preLoaderRoute: typeof ProjectsIdApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/approvals/$projectId': {
      id: '/client/approvals/$projectId'
      path: '/client/approvals/$projectId'
      fullPath: '/client/approvals/$projectId'
      preLoaderRoute: typeof ClientApprovalsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quickbooks/sync-invoice': {
      id: '/api/quickbooks/sync-invoice'
      path: '/api/quickbooks/sync-invoice'
      fullPath: '/api/quickbooks/sync-invoice'
      preLoaderRoute: typeof ApiQuickbooksSyncInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quickbooks/status': {
      id: '/api/quickbooks/status'
      path: '/api/quickbooks/status'
      fullPath: '/api/quickbooks/status'
      preLoaderRoute: typeof ApiQuickbooksStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quickbooks/project-link': {
      id: '/api/quickbooks/project-link'
      path: '/api/quickbooks/project-link'
      fullPath: '/api/quickbooks/project-link'
      preLoaderRoute: typeof ApiQuickbooksProjectLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quickbooks/disconnect': {
      id: '/api/quickbooks/disconnect'
      path: '/api/quickbooks/disconnect'
      fullPath: '/api/quickbooks/disconnect'
      preLoaderRoute: typeof ApiQuickbooksDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quickbooks/customers': {
      id: '/api/quickbooks/customers'
      path: '/api/quickbooks/customers'
      fullPath: '/api/quickbooks/customers'
      preLoaderRoute: typeof ApiQuickbooksCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quickbooks/connect-url': {
      id: '/api/quickbooks/connect-url'
      path: '/api/quickbooks/connect-url'
      fullPath: '/api/quickbooks/connect-url'
      preLoaderRoute: typeof ApiQuickbooksConnectUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quickbooks/callback': {
      id: '/api/quickbooks/callback'
      path: '/api/quickbooks/callback'
      fullPath: '/api/quickbooks/callback'
      preLoaderRoute: typeof ApiQuickbooksCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/projects': {
      id: '/api/extension/projects'
      path: '/api/extension/projects'
      fullPath: '/api/extension/projects'
      preLoaderRoute: typeof ApiExtensionProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/prices': {
      id: '/api/extension/prices'
      path: '/api/extension/prices'
      fullPath: '/api/extension/prices'
      preLoaderRoute: typeof ApiExtensionPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/import-product': {
      id: '/api/extension/import-product'
      path: '/api/extension/import-product'
      fullPath: '/api/extension/import-product'
      preLoaderRoute: typeof ApiExtensionImportProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/connect-token': {
      id: '/api/extension/connect-token'
      path: '/api/extension/connect-token'
      fullPath: '/api/extension/connect-token'
      preLoaderRoute: typeof ApiExtensionConnectTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/board-pages': {
      id: '/api/extension/board-pages'
      path: '/api/extension/board-pages'
      fullPath: '/api/extension/board-pages'
      preLoaderRoute: typeof ApiExtensionBoardPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/rooms/$roomId': {
      id: '/projects/$id/rooms/$roomId'
      path: '/projects/$id/rooms/$roomId'
      fullPath: '/projects/$id/rooms/$roomId'
      preLoaderRoute: typeof ProjectsIdRoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  FinancialsRoute: FinancialsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProcurementRoute: ProcurementRoute,
  ProjectManagementRoute: ProjectManagementRoute,
  TermsRoute: TermsRoute,
  ApiClientDashboardRoute: ApiClientDashboardRoute,
  ApiCreateStripePaymentLinkRoute: ApiCreateStripePaymentLinkRoute,
  ApiDesignBoardCommentTodosRoute: ApiDesignBoardCommentTodosRoute,
  ApiDesignBoardQuestionRoute: ApiDesignBoardQuestionRoute,
  ApiGenerateRenderingRoute: ApiGenerateRenderingRoute,
  ApiImageDataUrlRoute: ApiImageDataUrlRoute,
  ApiImportMaterialsPdfRoute: ApiImportMaterialsPdfRoute,
  ApiMarkFinancialPaymentDueRoute: ApiMarkFinancialPaymentDueRoute,
  ApiMyTodosRoute: ApiMyTodosRoute,
  ApiParseInvoicePdfRoute: ApiParseInvoicePdfRoute,
  ApiPresentationBoardRoute: ApiPresentationBoardRoute,
  ApiProjectManagementRoute: ApiProjectManagementRoute,
  ApiProjectTaskAttachmentRoute: ApiProjectTaskAttachmentRoute,
  ApiProjectTodosRoute: ApiProjectTodosRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiRemoveDesignBoardBackgroundRoute: ApiRemoveDesignBoardBackgroundRoute,
  ApiScrapeMaterialsRoute: ApiScrapeMaterialsRoute,
  ApiScrapeUrlRoute: ApiScrapeUrlRoute,
  ApiSharedDesignBoardRoute: ApiSharedDesignBoardRoute,
  ApiStudioRemindersRoute: ApiStudioRemindersRoute,
  ApiUploadDesignBoardImageRoute: ApiUploadDesignBoardImageRoute,
  ApiUploadProjectDocumentRoute: ApiUploadProjectDocumentRoute,
  ApiUploadRoomImageRoute: ApiUploadRoomImageRoute,
  ApiUsersRoute: ApiUsersRoute,
  CatalogProductIdRoute: CatalogProductIdRoute,
  ClientFinancialsRoute: ClientFinancialsRoute,
  ExtensionConnectRoute: ExtensionConnectRoute,
  PresentationsIdRoute: PresentationsIdRoute,
  PrototypeDesignBoardRoute: PrototypeDesignBoardRoute,
  SpecbooksIdRoute: SpecbooksIdRoute,
  HoursIndexRoute: HoursIndexRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SpecbooksIndexRoute: SpecbooksIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ApiExtensionBoardPagesRoute: ApiExtensionBoardPagesRoute,
  ApiExtensionConnectTokenRoute: ApiExtensionConnectTokenRoute,
  ApiExtensionImportProductRoute: ApiExtensionImportProductRoute,
  ApiExtensionPricesRoute: ApiExtensionPricesRoute,
  ApiExtensionProjectsRoute: ApiExtensionProjectsRoute,
  ApiQuickbooksCallbackRoute: ApiQuickbooksCallbackRoute,
  ApiQuickbooksConnectUrlRoute: ApiQuickbooksConnectUrlRoute,
  ApiQuickbooksCustomersRoute: ApiQuickbooksCustomersRoute,
  ApiQuickbooksDisconnectRoute: ApiQuickbooksDisconnectRoute,
  ApiQuickbooksProjectLinkRoute: ApiQuickbooksProjectLinkRoute,
  ApiQuickbooksStatusRoute: ApiQuickbooksStatusRoute,
  ApiQuickbooksSyncInvoiceRoute: ApiQuickbooksSyncInvoiceRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ClientApprovalsProjectIdRoute: ClientApprovalsProjectIdRoute,
  ProjectsIdApprovalsRoute: ProjectsIdApprovalsRoute,
  ProjectsIdConstructionDocsRoute: ProjectsIdConstructionDocsRoute,
  ProjectsIdDesignBoardPresentationRoute:
    ProjectsIdDesignBoardPresentationRoute,
  ProjectsIdDesignBoardsRoute: ProjectsIdDesignBoardsRoute,
  ProjectsIdFinancialsRoute: ProjectsIdFinancialsRoute,
  ProjectsIdMaterialsRoute: ProjectsIdMaterialsRoute,
  ProjectsIdPresentationRoute: ProjectsIdPresentationRoute,
  ProjectsIdRenderingsRoute: ProjectsIdRenderingsRoute,
  SpecbooksPublicIdRoute: SpecbooksPublicIdRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
  ProjectsIdRoomsRoomIdRoute: ProjectsIdRoomsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
