/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinancialsRouteImport } from './routes/financials'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as SpecbooksIndexRouteImport } from './routes/specbooks.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as PresentationsIndexRouteImport } from './routes/presentations.index'
import { Route as HoursIndexRouteImport } from './routes/hours.index'
import { Route as SpecbooksIdRouteImport } from './routes/specbooks.$id'
import { Route as PresentationsIdRouteImport } from './routes/presentations.$id'
import { Route as CatalogProductIdRouteImport } from './routes/catalog_.$productId'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiScrapeUrlRouteImport } from './routes/api/scrape-url'
import { Route as ApiScrapeMaterialsRouteImport } from './routes/api/scrape-materials'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiParseInvoicePdfRouteImport } from './routes/api/parse-invoice-pdf'
import { Route as ApiImportMaterialsPdfRouteImport } from './routes/api/import-materials-pdf'
import { Route as ApiGenerateRenderingRouteImport } from './routes/api/generate-rendering'
import { Route as ApiCreateStripePaymentLinkRouteImport } from './routes/api/create-stripe-payment-link'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects.$id.index'
import { Route as ProjectsIdRenderingsRouteImport } from './routes/projects.$id.renderings'
import { Route as ProjectsIdPresentationRouteImport } from './routes/projects.$id.presentation'
import { Route as ProjectsIdMaterialsRouteImport } from './routes/projects.$id.materials'
import { Route as ProjectsIdFinancialsRouteImport } from './routes/projects.$id.financials'
import { Route as ProjectsIdApprovalsRouteImport } from './routes/projects.$id.approvals'
import { Route as ClientApprovalsProjectIdRouteImport } from './routes/client.approvals.$projectId'
import { Route as ProjectsIdRoomsRoomIdRouteImport } from './routes/projects.$id.rooms.$roomId'

const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialsRoute = FinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecbooksIndexRoute = SpecbooksIndexRouteImport.update({
  id: '/specbooks/',
  path: '/specbooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIndexRoute = PresentationsIndexRouteImport.update({
  id: '/presentations/',
  path: '/presentations/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursIndexRoute = HoursIndexRouteImport.update({
  id: '/hours/',
  path: '/hours/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecbooksIdRoute = SpecbooksIdRouteImport.update({
  id: '/specbooks/$id',
  path: '/specbooks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationsIdRoute = PresentationsIdRouteImport.update({
  id: '/presentations/$id',
  path: '/presentations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogProductIdRoute = CatalogProductIdRouteImport.update({
  id: '/catalog_/$productId',
  path: '/catalog/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeUrlRoute = ApiScrapeUrlRouteImport.update({
  id: '/api/scrape-url',
  path: '/api/scrape-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeMaterialsRoute = ApiScrapeMaterialsRouteImport.update({
  id: '/api/scrape-materials',
  path: '/api/scrape-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseInvoicePdfRoute = ApiParseInvoicePdfRouteImport.update({
  id: '/api/parse-invoice-pdf',
  path: '/api/parse-invoice-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportMaterialsPdfRoute = ApiImportMaterialsPdfRouteImport.update({
  id: '/api/import-materials-pdf',
  path: '/api/import-materials-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRenderingRoute = ApiGenerateRenderingRouteImport.update({
  id: '/api/generate-rendering',
  path: '/api/generate-rendering',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateStripePaymentLinkRoute =
  ApiCreateStripePaymentLinkRouteImport.update({
    id: '/api/create-stripe-payment-link',
    path: '/api/create-stripe-payment-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRenderingsRoute = ProjectsIdRenderingsRouteImport.update({
  id: '/projects/$id/renderings',
  path: '/projects/$id/renderings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdPresentationRoute = ProjectsIdPresentationRouteImport.update({
  id: '/projects/$id/presentation',
  path: '/projects/$id/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdMaterialsRoute = ProjectsIdMaterialsRouteImport.update({
  id: '/projects/$id/materials',
  path: '/projects/$id/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdFinancialsRoute = ProjectsIdFinancialsRouteImport.update({
  id: '/projects/$id/financials',
  path: '/projects/$id/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdApprovalsRoute = ProjectsIdApprovalsRouteImport.update({
  id: '/projects/$id/approvals',
  path: '/projects/$id/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientApprovalsProjectIdRoute =
  ClientApprovalsProjectIdRouteImport.update({
    id: '/client/approvals/$projectId',
    path: '/client/approvals/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdRoomsRoomIdRoute = ProjectsIdRoomsRoomIdRouteImport.update({
  id: '/projects/$id/rooms/$roomId',
  path: '/projects/$id/rooms/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/financials': typeof FinancialsRoute
  '/login': typeof LoginRoute
  '/procurement': typeof ProcurementRoute
  '/api/create-stripe-payment-link': typeof ApiCreateStripePaymentLinkRoute
  '/api/generate-rendering': typeof ApiGenerateRenderingRoute
  '/api/import-materials-pdf': typeof ApiImportMaterialsPdfRoute
  '/api/parse-invoice-pdf': typeof ApiParseInvoicePdfRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/scrape-materials': typeof ApiScrapeMaterialsRoute
  '/api/scrape-url': typeof ApiScrapeUrlRoute
  '/api/users': typeof ApiUsersRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/presentations/$id': typeof PresentationsIdRoute
  '/specbooks/$id': typeof SpecbooksIdRoute
  '/hours/': typeof HoursIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/specbooks/': typeof SpecbooksIndexRoute
  '/users/': typeof UsersIndexRoute
  '/client/approvals/$projectId': typeof ClientApprovalsProjectIdRoute
  '/projects/$id/approvals': typeof ProjectsIdApprovalsRoute
  '/projects/$id/financials': typeof ProjectsIdFinancialsRoute
  '/projects/$id/materials': typeof ProjectsIdMaterialsRoute
  '/projects/$id/presentation': typeof ProjectsIdPresentationRoute
  '/projects/$id/renderings': typeof ProjectsIdRenderingsRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/rooms/$roomId': typeof ProjectsIdRoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/financials': typeof FinancialsRoute
  '/login': typeof LoginRoute
  '/procurement': typeof ProcurementRoute
  '/api/create-stripe-payment-link': typeof ApiCreateStripePaymentLinkRoute
  '/api/generate-rendering': typeof ApiGenerateRenderingRoute
  '/api/import-materials-pdf': typeof ApiImportMaterialsPdfRoute
  '/api/parse-invoice-pdf': typeof ApiParseInvoicePdfRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/scrape-materials': typeof ApiScrapeMaterialsRoute
  '/api/scrape-url': typeof ApiScrapeUrlRoute
  '/api/users': typeof ApiUsersRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/presentations/$id': typeof PresentationsIdRoute
  '/specbooks/$id': typeof SpecbooksIdRoute
  '/hours': typeof HoursIndexRoute
  '/presentations': typeof PresentationsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/specbooks': typeof SpecbooksIndexRoute
  '/users': typeof UsersIndexRoute
  '/client/approvals/$projectId': typeof ClientApprovalsProjectIdRoute
  '/projects/$id/approvals': typeof ProjectsIdApprovalsRoute
  '/projects/$id/financials': typeof ProjectsIdFinancialsRoute
  '/projects/$id/materials': typeof ProjectsIdMaterialsRoute
  '/projects/$id/presentation': typeof ProjectsIdPresentationRoute
  '/projects/$id/renderings': typeof ProjectsIdRenderingsRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/projects/$id/rooms/$roomId': typeof ProjectsIdRoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/financials': typeof FinancialsRoute
  '/login': typeof LoginRoute
  '/procurement': typeof ProcurementRoute
  '/api/create-stripe-payment-link': typeof ApiCreateStripePaymentLinkRoute
  '/api/generate-rendering': typeof ApiGenerateRenderingRoute
  '/api/import-materials-pdf': typeof ApiImportMaterialsPdfRoute
  '/api/parse-invoice-pdf': typeof ApiParseInvoicePdfRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/scrape-materials': typeof ApiScrapeMaterialsRoute
  '/api/scrape-url': typeof ApiScrapeUrlRoute
  '/api/users': typeof ApiUsersRoute
  '/catalog_/$productId': typeof CatalogProductIdRoute
  '/presentations/$id': typeof PresentationsIdRoute
  '/specbooks/$id': typeof SpecbooksIdRoute
  '/hours/': typeof HoursIndexRoute
  '/presentations/': typeof PresentationsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/specbooks/': typeof SpecbooksIndexRoute
  '/users/': typeof UsersIndexRoute
  '/client/approvals/$projectId': typeof ClientApprovalsProjectIdRoute
  '/projects/$id/approvals': typeof ProjectsIdApprovalsRoute
  '/projects/$id/financials': typeof ProjectsIdFinancialsRoute
  '/projects/$id/materials': typeof ProjectsIdMaterialsRoute
  '/projects/$id/presentation': typeof ProjectsIdPresentationRoute
  '/projects/$id/renderings': typeof ProjectsIdRenderingsRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/projects/$id/rooms/$roomId': typeof ProjectsIdRoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/financials'
    | '/login'
    | '/procurement'
    | '/api/create-stripe-payment-link'
    | '/api/generate-rendering'
    | '/api/import-materials-pdf'
    | '/api/parse-invoice-pdf'
    | '/api/projects'
    | '/api/scrape-materials'
    | '/api/scrape-url'
    | '/api/users'
    | '/catalog/$productId'
    | '/presentations/$id'
    | '/specbooks/$id'
    | '/hours/'
    | '/presentations/'
    | '/projects/'
    | '/specbooks/'
    | '/users/'
    | '/client/approvals/$projectId'
    | '/projects/$id/approvals'
    | '/projects/$id/financials'
    | '/projects/$id/materials'
    | '/projects/$id/presentation'
    | '/projects/$id/renderings'
    | '/projects/$id/'
    | '/projects/$id/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/financials'
    | '/login'
    | '/procurement'
    | '/api/create-stripe-payment-link'
    | '/api/generate-rendering'
    | '/api/import-materials-pdf'
    | '/api/parse-invoice-pdf'
    | '/api/projects'
    | '/api/scrape-materials'
    | '/api/scrape-url'
    | '/api/users'
    | '/catalog/$productId'
    | '/presentations/$id'
    | '/specbooks/$id'
    | '/hours'
    | '/presentations'
    | '/projects'
    | '/specbooks'
    | '/users'
    | '/client/approvals/$projectId'
    | '/projects/$id/approvals'
    | '/projects/$id/financials'
    | '/projects/$id/materials'
    | '/projects/$id/presentation'
    | '/projects/$id/renderings'
    | '/projects/$id'
    | '/projects/$id/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/financials'
    | '/login'
    | '/procurement'
    | '/api/create-stripe-payment-link'
    | '/api/generate-rendering'
    | '/api/import-materials-pdf'
    | '/api/parse-invoice-pdf'
    | '/api/projects'
    | '/api/scrape-materials'
    | '/api/scrape-url'
    | '/api/users'
    | '/catalog_/$productId'
    | '/presentations/$id'
    | '/specbooks/$id'
    | '/hours/'
    | '/presentations/'
    | '/projects/'
    | '/specbooks/'
    | '/users/'
    | '/client/approvals/$projectId'
    | '/projects/$id/approvals'
    | '/projects/$id/financials'
    | '/projects/$id/materials'
    | '/projects/$id/presentation'
    | '/projects/$id/renderings'
    | '/projects/$id/'
    | '/projects/$id/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  FinancialsRoute: typeof FinancialsRoute
  LoginRoute: typeof LoginRoute
  ProcurementRoute: typeof ProcurementRoute
  ApiCreateStripePaymentLinkRoute: typeof ApiCreateStripePaymentLinkRoute
  ApiGenerateRenderingRoute: typeof ApiGenerateRenderingRoute
  ApiImportMaterialsPdfRoute: typeof ApiImportMaterialsPdfRoute
  ApiParseInvoicePdfRoute: typeof ApiParseInvoicePdfRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiScrapeMaterialsRoute: typeof ApiScrapeMaterialsRoute
  ApiScrapeUrlRoute: typeof ApiScrapeUrlRoute
  ApiUsersRoute: typeof ApiUsersRoute
  CatalogProductIdRoute: typeof CatalogProductIdRoute
  PresentationsIdRoute: typeof PresentationsIdRoute
  SpecbooksIdRoute: typeof SpecbooksIdRoute
  HoursIndexRoute: typeof HoursIndexRoute
  PresentationsIndexRoute: typeof PresentationsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SpecbooksIndexRoute: typeof SpecbooksIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ClientApprovalsProjectIdRoute: typeof ClientApprovalsProjectIdRoute
  ProjectsIdApprovalsRoute: typeof ProjectsIdApprovalsRoute
  ProjectsIdFinancialsRoute: typeof ProjectsIdFinancialsRoute
  ProjectsIdMaterialsRoute: typeof ProjectsIdMaterialsRoute
  ProjectsIdPresentationRoute: typeof ProjectsIdPresentationRoute
  ProjectsIdRenderingsRoute: typeof ProjectsIdRenderingsRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
  ProjectsIdRoomsRoomIdRoute: typeof ProjectsIdRoomsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financials': {
      id: '/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof FinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specbooks/': {
      id: '/specbooks/'
      path: '/specbooks'
      fullPath: '/specbooks/'
      preLoaderRoute: typeof SpecbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/': {
      id: '/presentations/'
      path: '/presentations'
      fullPath: '/presentations/'
      preLoaderRoute: typeof PresentationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours/': {
      id: '/hours/'
      path: '/hours'
      fullPath: '/hours/'
      preLoaderRoute: typeof HoursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specbooks/$id': {
      id: '/specbooks/$id'
      path: '/specbooks/$id'
      fullPath: '/specbooks/$id'
      preLoaderRoute: typeof SpecbooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentations/$id': {
      id: '/presentations/$id'
      path: '/presentations/$id'
      fullPath: '/presentations/$id'
      preLoaderRoute: typeof PresentationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog_/$productId': {
      id: '/catalog_/$productId'
      path: '/catalog/$productId'
      fullPath: '/catalog/$productId'
      preLoaderRoute: typeof CatalogProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape-url': {
      id: '/api/scrape-url'
      path: '/api/scrape-url'
      fullPath: '/api/scrape-url'
      preLoaderRoute: typeof ApiScrapeUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape-materials': {
      id: '/api/scrape-materials'
      path: '/api/scrape-materials'
      fullPath: '/api/scrape-materials'
      preLoaderRoute: typeof ApiScrapeMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-invoice-pdf': {
      id: '/api/parse-invoice-pdf'
      path: '/api/parse-invoice-pdf'
      fullPath: '/api/parse-invoice-pdf'
      preLoaderRoute: typeof ApiParseInvoicePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-materials-pdf': {
      id: '/api/import-materials-pdf'
      path: '/api/import-materials-pdf'
      fullPath: '/api/import-materials-pdf'
      preLoaderRoute: typeof ApiImportMaterialsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-rendering': {
      id: '/api/generate-rendering'
      path: '/api/generate-rendering'
      fullPath: '/api/generate-rendering'
      preLoaderRoute: typeof ApiGenerateRenderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-stripe-payment-link': {
      id: '/api/create-stripe-payment-link'
      path: '/api/create-stripe-payment-link'
      fullPath: '/api/create-stripe-payment-link'
      preLoaderRoute: typeof ApiCreateStripePaymentLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/renderings': {
      id: '/projects/$id/renderings'
      path: '/projects/$id/renderings'
      fullPath: '/projects/$id/renderings'
      preLoaderRoute: typeof ProjectsIdRenderingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/presentation': {
      id: '/projects/$id/presentation'
      path: '/projects/$id/presentation'
      fullPath: '/projects/$id/presentation'
      preLoaderRoute: typeof ProjectsIdPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/materials': {
      id: '/projects/$id/materials'
      path: '/projects/$id/materials'
      fullPath: '/projects/$id/materials'
      preLoaderRoute: typeof ProjectsIdMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/financials': {
      id: '/projects/$id/financials'
      path: '/projects/$id/financials'
      fullPath: '/projects/$id/financials'
      preLoaderRoute: typeof ProjectsIdFinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/approvals': {
      id: '/projects/$id/approvals'
      path: '/projects/$id/approvals'
      fullPath: '/projects/$id/approvals'
      preLoaderRoute: typeof ProjectsIdApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/approvals/$projectId': {
      id: '/client/approvals/$projectId'
      path: '/client/approvals/$projectId'
      fullPath: '/client/approvals/$projectId'
      preLoaderRoute: typeof ClientApprovalsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/rooms/$roomId': {
      id: '/projects/$id/rooms/$roomId'
      path: '/projects/$id/rooms/$roomId'
      fullPath: '/projects/$id/rooms/$roomId'
      preLoaderRoute: typeof ProjectsIdRoomsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  FinancialsRoute: FinancialsRoute,
  LoginRoute: LoginRoute,
  ProcurementRoute: ProcurementRoute,
  ApiCreateStripePaymentLinkRoute: ApiCreateStripePaymentLinkRoute,
  ApiGenerateRenderingRoute: ApiGenerateRenderingRoute,
  ApiImportMaterialsPdfRoute: ApiImportMaterialsPdfRoute,
  ApiParseInvoicePdfRoute: ApiParseInvoicePdfRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiScrapeMaterialsRoute: ApiScrapeMaterialsRoute,
  ApiScrapeUrlRoute: ApiScrapeUrlRoute,
  ApiUsersRoute: ApiUsersRoute,
  CatalogProductIdRoute: CatalogProductIdRoute,
  PresentationsIdRoute: PresentationsIdRoute,
  SpecbooksIdRoute: SpecbooksIdRoute,
  HoursIndexRoute: HoursIndexRoute,
  PresentationsIndexRoute: PresentationsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SpecbooksIndexRoute: SpecbooksIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ClientApprovalsProjectIdRoute: ClientApprovalsProjectIdRoute,
  ProjectsIdApprovalsRoute: ProjectsIdApprovalsRoute,
  ProjectsIdFinancialsRoute: ProjectsIdFinancialsRoute,
  ProjectsIdMaterialsRoute: ProjectsIdMaterialsRoute,
  ProjectsIdPresentationRoute: ProjectsIdPresentationRoute,
  ProjectsIdRenderingsRoute: ProjectsIdRenderingsRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
  ProjectsIdRoomsRoomIdRoute: ProjectsIdRoomsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
