ALTER TABLE public.room_images
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'complete',
  ADD COLUMN IF NOT EXISTS role TEXT,
  ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_approved BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS error_message TEXT;